$pdf_mode = 1;
$pdflatex = 'texfot pdflatex -interaction=nonstopmode';
$pdf_previewer = 'xdg-open';
$out_dir = './build_latex';
@default_files = ('./main.tex');

$preview_continuous_mode = 1; #-pvc- in terminal to turn off this feature for the current command

